# Generated by Django 3.0.5 on 2020-05-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokemon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dex_num', models.IntegerField()),
                ('pokemon_name', models.CharField(max_length=100)),
                ('base_atk', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('base_sta', models.IntegerField()),
            ],
        ),
    ]
